faq/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.debug import default_urlconf

from posts.views import UserPostsView
from . import views
from django.contrib.sitemaps.views import sitemap
from qa.sitemap import QuestionSitemap


urlpatterns = [
    # Examples:
    url(r'^$', views.IndexView.as_view()),
    # url(r'^$', 'profit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^qa/', include("qa.urls", namespace="qa")),
    url(r'^posts/$', UserPostsView.as_view()),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {"faq": QuestionSitemap}}, name='django.contrib.sitemaps.views.sitemap')

]

# rest api
#
#urlpatterns += [    
#]

faq/qa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.debug import default_urlconf

from .utlis import cache_for_anonim
from . import views
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^(?P<pk>\d+)-(?P<slug>[\w-]+)/$', cache_for_anonim(60*5)(views.QuestionView.as_view()), name="question"),
    url(r'^sitemap/$', cache_for_anonim(60*5)(views.QuestionmapView.as_view()), name="questionmap"),
]

faq/posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    post_id = models.IntegerField(unique=True)
    date = models.DateField()
    username = models.CharField(max_length=255, db_index=True)
    full_body = models.TextField()
    body = models.TextField()

    class Meta:
        ordering = "-post_id",

faq/qa/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField
from simple_history import register


# Create your models here.


class Question(MPTTModel):
    name = models.CharField("Название", max_length=2048)
    button_name = models.CharField("Текст на кнопке", max_length=128, blank=True, help_text="Необзяательно, если что будет такое же как и название")
    slug = models.SlugField(max_length=128)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True, verbose_name="Родительский элемент")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    content = RichTextField(blank=True, verbose_name="Текст")
    deleted_at = models.DateTimeField(blank=True, null=True)

    id_development = models.BooleanField("В разработке", default=True, help_text="Это чтобы мы сами понимали что ещё осталось, и давали понять остальным. Когда кажется что всё готово - просто снять эту галочку")

    related = models.ManyToManyField("self", symmetrical=False, verbose_name="Связанные ссылки", blank=True, help_text="Другие ссылки, которые могут быть полезны в этом контексте.")

    def save(self, *args, **kwargs):
        if not self.button_name:
            self.button_name = self.name
        super(Question, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("qa:question", kwargs={"pk": self.pk, "slug": self.slug})

    def __str__(self):
        return "%s%s" % (self.button_name, (" [в разработке]" if self.id_development else ""))

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"


register(Question)

faq/core/views.py
from django.views.generic.base import RedirectView

from qa.models import Question


class IndexView(RedirectView):
    def get_redirect_url(self):
        return Question.objects.filter(parent__isnull=True).first().get_absolute_url()

faq/posts/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from .models import Post


class UserPostsView(ListView):
    model = Post

    def get_queryset(self):
        return super().get_queryset().filter(username=self.request.GET.get("author", "").strip())

faq/qa/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from . import models


class QuestionView(DetailView):
    model = models.Question
    queryset = models.Question.objects.filter(deleted_at__isnull=True)


class QuestionmapView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        data = super(QuestionmapView, self).get_context_data(**kwargs)
        data['root'] = models.Question.objects.all()
        return data

faq/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% endblock css %}
    {% block extra_css %}
    {% endblock extra_css %}
</head>

<body>
    {% block nav %} {% endblock nav %}

    <div class="container">
        {% block content %}
        {% endblock content %}

        <footer class="container">
            <nav class="nav">
                <a class="nav-link pt-1 pb-1" href="{% url "qa:questionmap" %}">Карта FAQ</a>
                <a class="nav-link pt-1 pb-1"
                   href="https://www.turpravda.ua/forums/discussion/189482/zaderzhka_vydachi_zagranpasporta">Форум
                    Турправда</a>
                <a class="nav-link pt-1 pb-1" href="https://www.facebook.com/groups/passportUA/">Группа "Паспорт-2017"</a>
                <a class="nav-link pt-1 pb-1" href="https://dmsu.gov.ua">Сайт ДМСУ</a>
                <a class="nav-link pt-1 pb-1" href="https://pk-ukraina.gov.ua">Сайт полиграфкомбината</a>
                <a class="nav-link pt-1 pb-1" href="https://www.facebook.com/STOPsvavilly/">СТОП свавіллю в паспортних столах</a>
            </nav>
        </footer>

    </div>

    {% block js %}
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% endblock js %}
    {% block extra_js %}
    {% endblock extra_js %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-48038077-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-48038077-2');
    </script>

</body>

</html>

faq/templates/index.html
{% extends "base.html" %}
{% load mptt_tags indent %}

{% block title %}Карта этого FAQ{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12 col-md-6">
            <h3>Карта этого FAQ</h3>
            <nav class="nav flex-column">
                {% recursetree root %}
                    <a class="nav-link pt-1 pb-1" href="{{ node.get_absolute_url }}">
                        {% indent node.level %}{{ node.button_name }}
                    {% if node.id_development %}<span class="badge badge-danger">В разработке</span> {% endif %}
                    </a>
                    {% if not node.is_leaf_node %}{{ children }}{% endif %}
                    {% if user.is_authenticated and user.is_staff %}
                        {% for i in node.related.all %}
                            <a class="nav-link pt-1 pb-1" href="{{ i.get_absolute_url }}">
                                {% indent 1 %}{% indent node.level %}{{ i.button_name }}
                            <span class="badge badge-light">Связанная ссылка</span>
                            {% if i.id_development %}<span class="badge badge-danger">В разработке</span> {% endif %}
                            </a>
                        {% endfor %}
                    {% endif %}
                {% endrecursetree %}
            </nav>
        </div>
    </div>

{% endblock content %}

faq/templates/posts/paginator.html
<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item disabled">
      <span class="page-link">Previous</span>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item active">
      <span class="page-link">
        2
        <span class="sr-only">(current)</span>
      </span>
    </li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>

faq/templates/posts/post_list.html
{% extends "base.html" %}
{% load admin_urls %}

{% block title %}{% if request.GET.author %}({{ object_list|length }}) {{ request.GET.author }}{% else %}Показать сообщения пользователя в теме{% endif %}{% endblock title %}

{% block content %}
    <header class="masthead">
        <div class="jumbotron p-3 mb-3">
            {% if request.GET.author %}
                <div class="bd-clipboard float-right position-relative ml-3">
                    <span class="badge badge-light">{{ request.GET.author }} - {{ object_list|length }}</span>
                </div>
            {% endif %}
            <form class="form-inline">
                <div class="form-group mx-sm-3">
                    <label for="author" class="sr-only">Username</label>
                    <input type="text" class="form-control" id="author" placeholder="Username" name="author">
                </div>
                <button type="submit" class="btn btn-primary">Показать сообщения</button>
            </form>
        </div>
    </header>

    <main role="main">
        {#                {% include "posts/paginator.html" %}#}

        {% for object in object_list %}
            <div class="jumbotron p-3 mb-3{% cycle '' ' bg-light' %}">
                <div class="bd-clipboard float-right position-relative ml-3">
                    <a class="badge badge-primary"
                       href="https://www.turpravda.ua/forums/discussion/comment/{{ object.post_id }}/#Comment_{{ object.post_id }}"
                       role="button">{{ object.date|date }}</a>
                </div>
                {{ object.body|safe }}
            </div>
        {% endfor %}
    </main>

    {#            {% include "posts/paginator.html" %}#}
{% endblock content %}

faq/templates/qa/question_detail.html
{% extends "base.html" %}
{% load admin_urls %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
    <header class="masthead">
        <ol class="breadcrumb">
            {% for i in object.get_ancestors %}
                <li class="breadcrumb-item"><a href="{{ i.get_absolute_url }}">{{ i.button_name }}</a></li>
            {% endfor %}
            <li class="breadcrumb-item active">{{ object.button_name }}</li>
        </ol>
    </header>

    <main role="main">

        <!-- Jumbotron -->
        <div class="jumbotron p-3 mb-3">
            {% if user.is_authenticated and user.is_staff %}
            <div class="bd-clipboard float-right position-relative">
                <a class="badge badge-light" href="{% url "admin:qa_question_change" object.id %}" role="button">Редактировать</a>
            </div>
            {% endif %}
            <h3>{% if object.id_development %}<span class="badge badge-danger">В разработке</span> {% endif %}{{ object.name }}</h3>
            {{ object.content|safe }}
        </div>

        <!-- Example row of columns -->
        <div class="row">
            {% for i in object.children.all %}
                <div class="col-12 col-lg-6 col-sm-12">
                    <p><a class="btn btn-info btn-block" href="{{ i.get_absolute_url }}" role="button">{{ i.button_name }}</a></p>
                </div>
            {% endfor %}
            {% for i in object.related.all %}
                <div class="col-12 col-lg-6 col-sm-12">
                    <p><a class="btn btn-info btn-block" href="{{ i.get_absolute_url }}" role="button">{{ i.button_name }}</a></p>
                </div>
            {% endfor %}
            {% if object.parent %}
                <div class="col-12 col-lg-6 col-sm-12">
                    <p><a class="btn btn-primary btn-block" href="{{ object.parent.get_absolute_url }}" role="button">Перейти на уровень выше</a></p>
                </div>
            {% endif %}
        </div>

    </main>
{% endblock content %}